version: "3.3"
    
services:
#Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: mysel-portfolio
    networks:
      - wpsite
  #phpMyadmin
  phpmyadmin:
    depends_on:
      - db
    restart: always
    image: phpmyadmin/phpmyadmin
    #domainname: example.com
    ports:
      - "8081:8081"
    environment:
      PMA_HOSTS: db
      #- PMA_VERBOSES=production-db1,production-db2,dev-db1,dev-db2
      PMA_USER: root
      PMA_PASSWORD: root
      #- PMA_ABSOLUTE_URI=http://example.com/phpmyadmin/
    networks:
    - wpsite
  #wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes: [./:/var/www/html]
    ports:
      - "8000:8000"
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_USER
    networks:
        - wpsite
networks:
  wpsite:
volumes:
  db_data: